[package]
name = "bister-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bister-spg = { path = "../bister-spg" }
bister-ir = { path = "../bister-ir" }
thiserror.workspace = true

[lints]
workspace = true
